### ISSUE TITLE
Existing files

### ISSUE THREAD

**Issue by Dontorpedo** [Movex-Ukraine/secure-array-files#2]
Hi,

how can i make it work with a existing App with "normal" File fields?

thanks

**Comment by oleksandr-roskovynskyi** [comment]
Hi! First, check if the field `$table->text('files')->nullable();` is used in the migration of the framework.
Next, you need to install this package: `composer require movex-ukraine/secure-array-files`

And then, just replace the standard file field with the field from the package:
use MovexUkraine\SecureArrayFiles\SecureArrayFiles;
```
public function fields(Request $request)
    {
        return [
            ...
            SecureArrayFiles::make('My files', 'files')
                ->disk('local')
                ->path('my_attachments'),
            ...
        ];
    }
```

Good luck!

**Comment by oleksandr-roskovynskyi** [comment]
> Hi,
> 
> how can i make it work with a existing App with "normal" File fields?
> 
> thanks

Unfortunately, existing files will have to be transferred manually if there are not many of them. You can also try to write an action to move values from an existing field to a new table field, but you will have to write the code for these actions yourself https://nova.laravel.com/docs/3.0/actions/defining-actions.html#overview. After the transfer, the old field can be deleted from the tables.

Format in which you need to convert data about your files:
```
[{
    "originalName":"favicon-32x32.png",
    "name":"my_attachments/2020-05-24_Yagdk7OFLNq3jb3wYp82LWmHtNNPOqc9VHGTdmkb.png",
    "url":"/storage/my_attachments/2020-05-24_Yagdk7OFLNq3jb3wYp82LWmHtNNPOqc9VHGTdmkb.png"
},
{
    "originalName":"robots.txt",
    "name":"my_attachments/2020-05-24_Rt1fHaMvxePXiH1NDqW6jBbwUR2yknVASfQQo0Kq.txt",
    "url":"/storage/my_attachments/2020-05-24_Rt1fHaMvxePXiH1NDqW6jBbwUR2yknVASfQQo0Kq.txt"
}]
```

**Comment by Dontorpedo** [comment]
ok, thank you
